backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
collections:
  - name: "project"
    label: "Proyectos"
    folder: "_projects/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}