backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
media_library:
  name: cloudinary
  config:
    cloud_name: dkvtpo8w1
    api_key: 773866779144732
    # default_transformations:
    #   - - fetch_format: auto
    #       width: 160
    #       quality: auto
    #       crop: scale
collections:
  - name: "project"
    label: "Proyectos"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Categoria", name: "category", widget: "select", "options": ["bodas", "general"]}
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: true
        media_library:
          config:
            default_transformations:
              - - fetch_format: auto
                  width: 500
                  quality: auto
                  crop: scale
      - label: Fotografias
        name: photos
        widget: list
        fields:
        - {label: "Fotografia", name: "photo", widget: "image"}