backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
media_library:
  name: cloudinary
  config:
    cloud_name: dkvtpo8w1
    api_key: 773866779144732
collections:
  - name: "project"
    label: "Proyectos"
    folder: "content/projects"
    create: true
    slug: "{{year}}_{{month}}_{{day}}_{{name}}"
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Categoria", name: "category", widget: "select", "options": ["bodas", "general"]}
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: true
        media_library:
          config:
            default_transformations:
              - - fetch_format: auto
                  width: 300
                  height: 500
                  quality: auto
                  crop: thumb
                  gravity: center
      - label: Galeria
        name: gallery
        widget: image
        required: false
        choose_url: false
        media_library:
          output_filename_only: true
          config:
            multiple: true
